### ISSUE TITLE
SIRF 3.7.0 Release Checklist

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF#1257]
## Release Checklist

```
VER=3.7.0
```

1. Submodules (within SIRF)
  - [x] tag data
    + `git submodule update` # **should not complain**
    + `cd data && git tag -a v$VER -m "version $VER" && git push --tags && cd ..`
    + `git status`  # **should not list `data` as modified**
2. SIRF
  - [x] update `CHANGES.md`
  - [x] update `NOTICE.txt`
  - [x] update `CITATION.cff`
  - [x] update version numbers in [SIRF/CMakeLists.txt](https://github.com/SyneRBI/SIRF/blob/master/CMakeLists.txt)
  - [x] update version numbers in the [doc/UsersGuide.md](https://github.com/SyneRBI/SIRF/blob/master/doc/UserGuide.md) etc
  - [x] run all demos
  - [x] run ctest
  - [x] `git push`
  - [x] check the build
  - [x] run doxygen, check, send files for uploading and update the doxygen link on Wiki
  - [x] `git tag -a v$VER -m "version $VER"`
  - [x] `git push origin v$VER`
  - [x] if final release only: create release on https://github.com/SyneRBI/SIRF/releases/new linked to the tag and copying all CHANGES.md since last release (as listed on https://github.com/SyneRBI/SIRF/releases)
3. SuperBuild
  - [x] update `CHANGES.md`
  - [x] update `NOTICE.txt`
  - [x] update `CITATION.cff`
  - [x] update `SIRF-Superbuild/version_config.cmake` with new `SIRF_TAG` (and `STIR_TAG` etc if necessary)
  - [x] https://github.com/SyneRBI/SIRF-SuperBuild/pull/897 (will have conflicts on SIRF_TAG with the previous one). 
  - [x] Sadly, ROOT still fails to compile so we need https://github.com/SyneRBI/SIRF-SuperBuild/pull/901 at the moment.
  - [x] update version number in [VM_version.txt](https://github.com/SyneRBI/SyneRBI_VM/blob/master/VM_version.txt)
  - [x] update `vb.name` in [vagrant/vagrantfile](https://github.com/SyneRBI/SyneRBI_VM/blob/master/vagrant/Vagrantfile)
  - [x] `git push`
  - [x] check the build
  - [x] `git tag -a v$VER -m "version $VER"`
  - [x] `git push origin v$VER`
  - [x] if final release only: create release on https://github.com/SyneRBI/SIRF-SuperBuild/releases/new linked to the tag and copying all CHANGES.md since last release (as listed on https://github.com/SyneRBI/SIRF-SuperBuild/releases)
4. SIRF-Contribs
  - [x] `git tag -a v$VER -m "version $VER"`
  - [x] `git push origin v$VER`
5. Virtual Machine
  - [ ] `vagrant up`
  - [ ] Virtualbox Guest Additions
  - [ ] run `first_run.sh` script (gnome settings and zero-fill trick)
  - [ ] check that the serial port is [deselected](https://github.com/SyneRBI/SyneRBI_VM/blob/master/vagrant/README.md#notes-about-ubuntu-box-for-version-100).
  - [ ] export the VM
  - [ ] ctest on VM
  - [ ] run all exercises (download data first)
  - [ ] upload to Zenodo
        * use name like `SIRF 2.2.0.ova` (with space) as Zenodo uses alphabetical ordering probably, add `-release-candidate-1` if necessary (as most people will not know what `rc1` means).
6. SIRF-Exercises (already checked in VM)
  - [x] `git tag -a v$VER -m "version $VER"`
  - [x] `git push origin v$VER`
7. Website (if final release)
  - [x] update Software page (version info, VM etc)
  - [x] upload doxygen
  - [x] update link for doxygen in [Wiki](https://github.com/SyneRBI/SIRF/wiki/Software-Documentation)
  - [x] add news flash
8. Announce
  - [x] Send email to SyneRBI-DEVEL@JISCMAIL.AC.UK; SyneRBI-USERS@JISCMAIL.AC.UK; add SyneRBI@JISCMAIL.AC.UK for final release
9. Tag wiki
  - [x] `git clone https://github.com/SyneRBI/SIRF.wiki.git; cd SIRF.wiki` (or pull)
  - [x] `git tag -a v$VER -m "version $VER"`
  - [x] `git push origin v$VER`

**Comment by KrisThielemans** [comment]
I've done final textual changes on the SIRF-SuperBuild.

@evgueni-ovtchinnikov what's stopping you from tagging SIRF? Once done, finishing off the SuperBuild and other tagging will be trivial.

Given current work-load, I suggest we don't do the VM at the moment (it could be trivial, but...). We can tell people to use `update_VM.sh -s` in their current VM.

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans I believe we should merge PR #1241 first (and Challenge24 PR #3) so that Challenge participants will use SIRF 3.7.0, should we not?

**Comment by KrisThielemans** [comment]
I think #1241 will likely take more time (I've just reviewed it). I've also created #1259 which I'd like to have for the challenge (for at least a few things).

So I think we should release 3.7/0 now,

**Comment by KrisThielemans** [comment]
I've tagged SIRF-Contribs and SIRF-Exercises. I've created https://github.com/SyneRBI/SIRF-SuperBuild/pull/902.
@casperdcl @paskino I believe we need https://github.com/SyneRBI/SIRF-SuperBuild/pull/897 (will have conflicts on SIRF_TAG with the previous one).  Sadly, ROOT still fails to compile so we need https://github.com/SyneRBI/SIRF-SuperBuild/pull/898 at the moment.
@paskino, @casperdcl can you finish those ?
