### ISSUE TITLE
Release 2.2.0 checklist

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#704]
```
VER=2.2.0
```
1. Submodules (within SIRF)
  - [x] tag data
    + `git submodule update` # **should not complain**
    + `cd data && git tag -a v$VER -m "version $VER" && git push --tags && cd ..`
    + `git status`  # **should not list `data` as modified**
2. SIRF
  - [x] update `CHANGES.md`
  - [x] update `NOTICE.txt`
  - [x] update `.zenodo.json`
  - [x] update version numbers in [SIRF/CMakeLists.txt](https://github.com/SyneRBI/SIRF/blob/master/CMakeLists.txt)
  - [x] update version numbers in the [doc/UsersGuide.md](https://github.com/SyneRBI/SIRF/blob/master/doc/UserGuide.md) etc
  - [x] run all demos
  - [x] run ctest
  - [x] `git push`
  - [x] check Travis
  - [x] run doxygen, check, send files for uploading and update the doxygen link on Wiki
  - [x] `git tag -a v$VER -m "version $VER"`
  - [x] `git push origin v$VER`
  - [x] create release on https://github.com/SyneRBI/SIRF/releases/new linked to the tag and copying all CHANGES.md since last release (as listed on https://github.com/SyneRBI/SIRF/releases)
3. SuperBuild
  - [x] update `CHANGES.md`
  - [x] update `NOTICE.txt`
  - [x] update `SIRF-Superbuild/version_config.cmake` with new `SIRF_TAG` (and `STIR_TAG` etc if necessary)
  - [x] `git push`
  - [x] check Travis
  - [x] `git tag -a v$VER -m "version $VER"`
  - [x] `git push origin v$VER`
4. Virtual Machine
  - [x] update version number in [VM_version.txt](https://github.com/SyneRBI/SyneRBI_VM/blob/master/VM_version.txt)
  - [x] update `vb.name` in [vagrant/vagrantfile](https://github.com/SyneRBI/SyneRBI_VM/blob/master/vagrant/Vagrantfile)
  - [x] update `CHANGES.md`
  - [x] update `NOTICE.txt`
  - [x] `git push`
  - [x] `vagrant up`
  - [x] Virtualbox Guest Additions
  - [x] run `first_run.sh` script (gnome settings and zero-fill trick)
  - [x] check that the serial port is [deselected](https://github.com/SyneRBI/SyneRBI_VM/blob/master/vagrant/README.md#notes-about-ubuntu-box-for-version-100).
  - [x] export the VM
  - [x] ctest on VM
  - [x] run all exercises (download data first)
  - [x] upload to Zenodo
  - [x] `git tag -a v$VER -m "version $VER"`
  - [x] `git push origin v$VER`
5. SIRF-Exercises (already checked in VM)
  - [x] `git tag -a v$VER -m "version $VER"`
  - [x] `git push origin v$VER`
6. SIRF-Contribs
  - [x] `git tag -a v$VER -m "version $VER"`
  - [x] `git push origin v$VER`
7. Website (if final release)
  - [x] update Software page (version info, VM etc)
  - [x] upload doxygen
  - [x] update link for doxygen in [Wiki](https://github.com/SyneRBI/SIRF/wiki/Software-Documentation)
  - [x] add news flash
8. Announce
  - [x] Send email to SyneRBI-DEVEL@JISCMAIL.AC.UK; SyneRBI-USERS@JISCMAIL.AC.UK; add SyneRBI@JISCMAIL.AC.UK for final release
9. Tag wikis
  - [x] `git clone https://github.com/SyneRBI/SIRF.wiki.git; cd SIRF.wiki` (or pull)
  - [x] `git tag -a v$VER -m "version $VER"`
  - [x] `git push origin v$VER`
  - [x] `git clone https://github.com/SyneRBI/SyneRBI_VM.wiki.git; cd SyneRBI_VM.wiki` (or pull)
  - [x] `git tag -a v$VER -m "version $VER"`
  - [x] `git push origin v$VER`

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov can you look at the remaining SIRF ticks?

@rijobro can you do SIRF-Exercises once done with your fixes?

@paskino as soon as https://github.com/SyneRBI/SIRF-SuperBuild/pull/409 is merged, you could start with the VM.

**Comment by rijobro** [comment]
> @rijobro can you do SIRF-Exercises once done with your fixes?

I've done SIRF-Exercises. 

I've noticed something funny for our SB releases: https://github.com/SyneRBI/SIRF-SuperBuild/releases. It shows all tags (you might need to click "Show x newer tags"), but it states our latest release as v2.0.0, and latest pre-release as v2.1.0-rc.3, both of which are wrong.

Seems we've done something wrong in recent releases that means that these aren't getting updated. Once we figure out what it is, that should presumably go into the checklist so that we don't get it wrong again.

**Comment by casperdcl** [comment]
you have to actually "add release notes" to a tag on the releases page, otherwise GitHub won't really count it as a release, naturally. Could just copy-paste from `CHANGES.md`

**Comment by rijobro** [comment]
Is there a way to do that from command line or it has to be from the github interface?

**Comment by KrisThielemans** [comment]
Even if it could be done on command line, it needs some thought on what to put in there. I found for instances that our SIRF CHANGES.md is a bit messy (roughly chronological order), so I've reordered text on the release page. Arguably I should have done it in CHANGES.md as well...

@paskino, can you please take care of creating the past SB releases? You have to do it in chronological order, as github doesn't do any smart ordering. (after the VM of course). Also update the SIRF checklist. Please create a maintainer issue for this.

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov could you tick the `doxygen` boxes (or fix them) and close this issue then?

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans  done (actually doxygen was done a while ago but I ticked in Section 2 only)
